package notify

import (
	"fmt"
	"net/smtp"

	"stockmarket/internal/models"
)

// EmailNotifier sends notifications via email (SMTP)
type EmailNotifier struct {
	host     string
	port     string
	username string
	password string
	from     string
}

// NewEmailNotifier creates a new email notifier
func NewEmailNotifier(config map[string]string) *EmailNotifier {
	return &EmailNotifier{
		host:     config["smtp_host"],
		port:     config["smtp_port"],
		username: config["smtp_username"],
		password: config["smtp_password"],
		from:     config["from_email"],
	}
}

// Type returns the notifier type
func (e *EmailNotifier) Type() string {
	return "email"
}

// Send sends an email notification
func (e *EmailNotifier) Send(notification models.Notification, target string) error {
	if e.host == "" {
		// Log but don't fail - email not configured
		fmt.Printf("[EMAIL] Would send to %s: %s - %s\n", target, notification.Title, notification.Message)
		return nil
	}

	auth := smtp.PlainAuth("", e.username, e.password, e.host)

	msg := fmt.Sprintf("From: %s\r\n"+
		"To: %s\r\n"+
		"Subject: %s\r\n"+
		"Content-Type: text/html; charset=UTF-8\r\n"+
		"\r\n"+
		"%s", e.from, target, notification.Title, formatEmailBody(notification))

	err := smtp.SendMail(
		e.host+":"+e.port,
		auth,
		e.from,
		[]string{target},
		[]byte(msg),
	)

	if err != nil {
		return fmt.Errorf("%w: %v", ErrNotificationFailed, err)
	}

	return nil
}

func formatEmailBody(n models.Notification) string {
	return fmt.Sprintf(`
		<html>
		<body style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
			<div style="background: #1a1a2e; color: white; padding: 20px; text-align: center;">
				<h1 style="margin: 0;">📈 Stock Alert</h1>
			</div>
			<div style="padding: 20px; background: #f5f5f5;">
				<h2 style="color: #333;">%s</h2>
				<p style="font-size: 16px; color: #666;">Symbol: <strong>%s</strong></p>
				<p style="font-size: 16px; color: #666;">%s</p>
			</div>
			<div style="padding: 10px; background: #eee; text-align: center; font-size: 12px; color: #999;">
				Generated by Stock Market Analysis Platform
			</div>
		</body>
		</html>
	`, n.Title, n.Symbol, n.Message)
}
